model = "gpt-6-astra"
model_reasoning_effort = "low"
service_tier = "default"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[tui]
theme = "monokai-extended-origin"
status_line = [
  "status",
  "project-name",
  "model-with-reasoning",
  "git-branch",
  "current-dir",
  "context-used",
]

[projects."/home/t4ko/dotfiles"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522/course-cli"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/zunoser/nakasyou-bakery-mod"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522/vodai"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/spotify-cli"]
trust_level = "trusted"

[projects."/home/t4ko/Project/Unity/amatousagi"]
trust_level = "trusted"

[projects."/home/t4ko"]
trust_level = "trusted"

[projects."/home/t4ko/Project/unity/amatousagi"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522/cf-edgeNix"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/T4ko0522"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/University-exams"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/cf-edgeNix"]
trust_level = "trusted"

[projects."/home/t4ko/game"]
trust_level = "trusted"

[projects."/home/t4ko/Project/github.com/t4ko0522/voiceloop"]
trust_level = "trusted"
