version: "1"
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - gocheckcompilerdirectives
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  disable:
    - errcheck
    - usestdlibvars
  settings:
    govet:
      disable:
        - unusedresult
    staticcheck:
      checks:
        - all
severity:
  default: error
  rules:
    - linters:
        - gofmt
        - goimports
        - intrange
      severity: info
formatters:
  enable:
    - gofmt
    - gofumpt